from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID

from sot.domain.models import (
    Branch,
    Cite,
    Document,
    Proposal,
    Revision,
    Session,
    Toss,
    Turn,
)


class SOTRepository(Protocol):
    def transaction(self) -> AbstractAsyncContextManager[None]: ...

    async def save_document(self, document: Document) -> None: ...

    async def get_document(self, document_id: UUID) -> Document | None: ...

    async def list_documents(self) -> tuple[Document, ...]: ...

    async def save_revision(self, revision: Revision) -> None: ...

    async def get_revision(self, revision_id: UUID) -> Revision | None: ...

    async def list_revisions(self, document_id: UUID) -> tuple[Revision, ...]: ...

    async def save_session(self, session: Session) -> None: ...

    async def get_session(self, session_id: UUID) -> Session | None: ...

    async def list_sessions(self, document_id: UUID) -> tuple[Session, ...]: ...

    async def save_branch(self, branch: Branch) -> None: ...

    async def get_branch(self, branch_id: UUID) -> Branch | None: ...

    async def list_branches(self, session_id: UUID) -> tuple[Branch, ...]: ...

    async def append_turns(self, turns: tuple[Turn, ...]) -> None: ...

    async def list_turns(self, branch_id: UUID) -> tuple[Turn, ...]: ...

    async def get_turns(self, turn_ids: tuple[UUID, ...]) -> tuple[Turn, ...]: ...

    async def save_cite(self, cite: Cite) -> None: ...

    async def get_cite(self, cite_id: UUID) -> Cite | None: ...

    async def list_cites(self, branch_id: UUID) -> tuple[Cite, ...]: ...

    async def save_toss(self, toss: Toss) -> None: ...

    async def get_toss_by_token(self, token: str) -> Toss | None: ...

    async def save_proposal(self, proposal: Proposal) -> None: ...

    async def get_proposal(self, proposal_id: UUID) -> Proposal | None: ...

    async def list_proposals(self, branch_id: UUID) -> tuple[Proposal, ...]: ...

    async def add_approval(self, proposal_id: UUID, actor_id: str) -> None: ...

    async def list_approvals(self, proposal_id: UUID) -> tuple[str, ...]: ...


__all__ = ["SOTRepository"]
